# - When there is a push to master, it automatically builds the image and uses the `latest` tag
# - On a `pull_request`, it automatically builds the image and sets the image tag by reading the `workflow.env` file which should have an entry like `DOCKER_IMAGE_TAG=1.0.0`
# - You can manually build an image via the Run Workflow option in Actions and specify the image tag in the form

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image Tag'
        required: true
        default: 'latest'

env:
  DOCKER_IMAGE_TAG: latest
  DOCKERHUB_USERNAME: stephens
  DOCKER_IMAGE_NAME: stephens/mqtt2prometheus

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Import environment variables from a file
        id: import-env
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < workflow.env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
